/**
 * Bot response texts in multiple languages
 */
const TEXTS = {
  uz: {
    welcome: '<b>MedPediatr botiga xush kelibsiz!</b> 👋\n\nBu yerda siz mutaxassislar bilan bog\'lanishingiz, savollaringizga javob olishingiz yoki qabulga yozilishingiz mumkin.',
    askDoctor: '👨‍⚕️ Mutaxassis bilan bog\'lanishni istaysizmi?',
    chooseSpecialist: '🔍 Kerakli mutaxassisni tanlang:',
    chooseBookingDoctor: '📅 Qaysi mutaxassis qabuliga yozilmoqchisiz?',
    wait: '⏳ Biroz kuting, ma\'lumotlar yuklanmoqda...',
    noDoctor: 'Tushunarli. Agar biror savolingiz bo\'lsa, bemalol murojaat qilishingiz mumkin. 😊',
    chatClosed: '✅ Chat yakunlandi. Yangi murojaat uchun menyudan foydalaning.',
    supportUnavailable: '⚠️ Operator hozircha ulanmagan. Iltimos, keyinroq urinib ko\'ring.',
    ownerOnly: '🚫 Bu buyruq faqat administratorlar uchun.',
    ownerSaved: (userId) => `✅ Owner ID muvaffaqiyatli saqlandi: <code>${userId}</code>`,
    chatStarted: (doctorName) => `<b>${doctorName}</b> tanlandi.\n\n📝 Endi savolingizni matn, rasm, video yoki audio ko'rinishida yuborishingiz mumkin.`,
    sentToSpecialist: (doctorName) => `📩 Xabaringiz <b>${doctorName}</b> uchun operatorga yuborildi. Javobni shu yerda olasiz.`,
    specialistReplyPrefix: (doctorName) => `💬 <b>${doctorName} javobi:</b>`,
    help: '<b>Botdan foydalanish bo\'yicha qo\'llanma:</b>\n\n/start - Bosh menyu\n/doctors - Mutaxassislar\n/book - Qabulga yozilish\n/help - Yordam\n/myid - Sizning ID\n/cancel - Bekor qilish',
    emergency: '⚠️ <b>MUHIM:</b> Bot shoshilinch yordam o\'rnini bosmaydi. Vaziyat og\'ir bo\'lsa, <b>103</b> ga qo\'ng\'iroq qiling!',
    bookingCancelled: '❌ Qabulga yozilish bekor qilindi.',
    askPatientName: '👤 Bemorning ism-sharifini yuboring:',
    askPatientAge: '🔢 Bemorning yoshini kiriting:',
    askPhone: '📞 Bog\'lanish uchun telefon raqami (+998XXXXXXXXX):',
    askComplaint: '📝 Shikoyat yoki murojaat sababini yozing:',
    invalidAge: '⚠️ Yoshni raqamda kiriting.',
    invalidPhone: '⚠️ Telefon raqami noto\'g\'ri.',
    bookingCreated: (doctorName, slot) => `✅ <b>${doctorName}</b> qabuliga <b>${slot}</b> vaqtiga so'rov qabul qilindi.`,
    bookingReplyPrefix: '🔔 <b>Bron bo\'yicha javob:</b>',
    noPendingBookings: '📭 Hozircha bronlar yo\'q.',
    chooseLang: '🌐 Tilni tanlang / Выберите язык:',
  },
  ru: {
    welcome: '<b>Добро пожаловать в MedPediatr bot!</b> 👋\n\nЗдесь вы можете связаться со специалистами, получить ответы на вопросы или записаться на прием.',
    askDoctor: '👨‍⚕️ Хотите связаться со специалистом?',
    chooseSpecialist: '🔍 Выберите нужного специалиста:',
    chooseBookingDoctor: '📅 К какому специалисту вы хотите записаться?',
    wait: '⏳ Пожалуйста, подождите, данные загружаются...',
    noDoctor: 'Понятно. Если возникнут вопросы, обращайтесь. 😊',
    chatClosed: '✅ Чат завершен. Используйте меню для нового обращения.',
    supportUnavailable: '⚠️ Оператор пока не подключен. Пожалуйста, попробуйте позже.',
    ownerOnly: '🚫 Эта команда только для администраторов.',
    ownerSaved: (userId) => `✅ Owner ID успешно сохранен: <code>${userId}</code>`,
    chatStarted: (doctorName) => `Выбран <b>${doctorName}</b>.\n\n📝 Теперь вы можете отправить свой вопрос в виде текста, фото, видео или аудио.`,
    sentToSpecialist: (doctorName) => `📩 Ваше сообщение для <b>${doctorName}</b> отправлено оператору. Ответ придет сюда.`,
    specialistReplyPrefix: (doctorName) => `💬 <b>Ответ ${doctorName}:</b>`,
    help: '<b>Руководство по использованию:</b>\n\n/start - Главное меню\n/doctors - Список врачей\n/book - Запись на прием\n/help - Помощь\n/myid - Ваш ID\n/cancel - Отмена',
    emergency: '⚠️ <b>ВАЖНО:</b> Бот не заменяет скорую помощь. При критических ситуациях звоните <b>103</b>!',
    bookingCancelled: '❌ Запись отменена.',
    askPatientName: '👤 Введите ФИО пациента:',
    askPatientAge: '🔢 Введите возраст пациента:',
    askPhone: '📞 Введите номер телефона (+998XXXXXXXXX):',
    askComplaint: '📝 Кратко опишите проблему:',
    invalidAge: '⚠️ Введите возраст числом.',
    invalidPhone: '⚠️ Номер телефона введен неверно.',
    bookingCreated: (doctorName, slot) => `✅ Запрос на прием к <b>${doctorName}</b> на <b>${slot}</b> принят.`,
    bookingReplyPrefix: '🔔 <b>Ответ по бронированию:</b>',
    noPendingBookings: '📭 Пока нет активных записей.',
    chooseLang: '🌐 Выберите язык / Tilni tanlang:',
  }
};

module.exports = TEXTS;
